version: "3.8"
services:
    # authentication:
    #     build:
    #         context: .
    #         dockerfile: authentication/Dockerfile
    #     environment:
    #         FLASK_ENV: development
    #     image: authentication
    #     ports:
    #         - 5000:5000
    #     depends_on:
    #         - db-auth
    #     networks:
    #         - mynetwork

    api_gateway:
        build:
            context: .
            dockerfile: api_gateway/Dockerfile
        environment:
            FLASK_ENV: development
        image: api_gateway
        ports:
            - 5001:5001
        networks:
            - mynetwork

    db-auth:
        image: mysql:8.0
        container_name: db-auth
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: 123
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: authentication
        ports:
            - "3307:3306"
        volumes:
            - db_auth_data:/var/lib/mysql
        networks:
            - mynetwork

    event_management_service:
        build:
            context: .
            dockerfile: event_management_service/Dockerfile
        environment:
            FLASK_ENV: development
        depends_on:
            - db
        image: event_management_service
        ports:
            - 5002:5002
        networks:
            - mynetwork

    db:
        image: mysql:8.0
        container_name: mysql-db
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: 123
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: event_management
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    # nginx:
    #     image: nginx:latest
    #     container_name: nginx
    #     ports:
    #         - "443:443"
    #     volumes:
    #         - ./nginx.conf:/etc/nginx/nginx.conf
    #         - ./ssl:/etc/nginx/ssl
    #     depends_on:
    #         - authentication

volumes:
    db_auth_data:
    db_event_data:
    db_data:

networks:
    mynetwork:
        driver: bridge