version: "3.8"
services:
    authentication:
        build:
            context: .
            dockerfile: authentication/Dockerfile
        environment:
            FLASK_ENV: development
        image: authentication
        ports:
            - 5000:5000
        depends_on:
            - db-auth
        networks:
            - mynetwork

    db-auth:
        image: mysql:8.0
        container_name: db-auth
        environment:
            # MYSQL_USER: root
            # MYSQL_PASSWORD: 123
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: authentication
        ports:
            - "3307:3306"
        volumes:
            - db_auth_data:/var/lib/mysql
        networks:
            - mynetwork

    db-ticket:
        image: mysql:8.0
        container_name: db-ticket
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: ticket_management
        ports:
            - "3308:3306"
        volumes:
            - db_ticket_data:/var/lib/mysql
        networks:
            - mynetwork

    db:
        image: mysql:8.0
        container_name: mysql-db
        environment:
            # MYSQL_USER: root
            # MYSQL_PASSWORD: 123
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: event_management
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_auth_data:
    db_ticket_data:
    db_data:

networks:
    mynetwork:
        driver: bridge