"""empty message

Revision ID: 21dbfbd493e5
Revises: 
Create Date: 2024-06-23 11:16:30.639364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21dbfbd493e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incentive',
    sa.Column('incentive_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('incentive_id')
    )
    op.create_table('promotion',
    sa.Column('promotion_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('promotion_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promotion')
    op.drop_table('incentive')
    # ### end Alembic commands ###
