# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ticket_management.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17ticket_management.proto\"\x8c\x01\n\x06Ticket\x12\x11\n\tticket_id\x18\x01 \x01(\x05\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\x12\x13\n\x0bticket_type\x18\x03 \x01(\t\x12\x14\n\x0cticket_price\x18\x04 \x01(\x02\x12\x16\n\x0etotal_quantity\x18\x05 \x01(\x05\x12\x1a\n\x12\x61vailable_quantity\x18\x06 \x01(\x05\"\x80\x01\n\rTicketRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x13\n\x0bticket_type\x18\x02 \x01(\t\x12\x14\n\x0cticket_price\x18\x03 \x01(\x02\x12\x16\n\x0etotal_quantity\x18\x04 \x01(\x05\x12\x1a\n\x12\x61vailable_quantity\x18\x05 \x01(\x05\")\n\x0eTicketResponse\x12\x17\n\x06ticket\x18\x01 \x01(\x0b\x32\x07.Ticket\"\x16\n\x14GetAllTicketsRequest\"1\n\x15GetAllTicketsResponse\x12\x18\n\x07tickets\x18\x01 \x03(\x0b\x32\x07.Ticket\"(\n\x13\x44\x65leteTicketRequest\x12\x11\n\tticket_id\x18\x01 \x01(\x05\"\'\n\x14\x44\x65leteTicketResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xe4\x01\n\rTicketService\x12,\n\tAddTicket\x12\x0e.TicketRequest\x1a\x0f.TicketResponse\x12(\n\x0cUpdateTicket\x12\x07.Ticket\x1a\x0f.TicketResponse\x12>\n\rGetAllTickets\x12\x15.GetAllTicketsRequest\x1a\x16.GetAllTicketsResponse\x12;\n\x0c\x44\x65leteTicket\x12\x14.DeleteTicketRequest\x1a\x15.DeleteTicketResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ticket_management_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TICKET']._serialized_start=28
  _globals['_TICKET']._serialized_end=168
  _globals['_TICKETREQUEST']._serialized_start=171
  _globals['_TICKETREQUEST']._serialized_end=299
  _globals['_TICKETRESPONSE']._serialized_start=301
  _globals['_TICKETRESPONSE']._serialized_end=342
  _globals['_GETALLTICKETSREQUEST']._serialized_start=344
  _globals['_GETALLTICKETSREQUEST']._serialized_end=366
  _globals['_GETALLTICKETSRESPONSE']._serialized_start=368
  _globals['_GETALLTICKETSRESPONSE']._serialized_end=417
  _globals['_DELETETICKETREQUEST']._serialized_start=419
  _globals['_DELETETICKETREQUEST']._serialized_end=459
  _globals['_DELETETICKETRESPONSE']._serialized_start=461
  _globals['_DELETETICKETRESPONSE']._serialized_end=500
  _globals['_TICKETSERVICE']._serialized_start=503
  _globals['_TICKETSERVICE']._serialized_end=731
# @@protoc_insertion_point(module_scope)
