version: '3.8'

services:
  db:
    image: mysql:5.7.22
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: promotion
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: promotion-container
    volumes:
      - .:/app
    # environment:
    #   DB_HOST: mysql
    #   DB_NAME: promotion
    #   DB_USER: root
    #   DB_PASSWORD: root
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
