# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import event_management_pb2 as event__management__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in event_management_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class EventManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEvent = channel.unary_unary(
                '/event_management.EventManagement/CreateEvent',
                request_serializer=event__management__pb2.Event.SerializeToString,
                response_deserializer=event__management__pb2.EventResponse.FromString,
                _registered_method=True)
        self.UpdateEvent = channel.unary_unary(
                '/event_management.EventManagement/UpdateEvent',
                request_serializer=event__management__pb2.Event.SerializeToString,
                response_deserializer=event__management__pb2.EventResponse.FromString,
                _registered_method=True)
        self.GetEvent = channel.unary_unary(
                '/event_management.EventManagement/GetEvent',
                request_serializer=event__management__pb2.EventID.SerializeToString,
                response_deserializer=event__management__pb2.Event.FromString,
                _registered_method=True)
        self.SearchEvents = channel.unary_unary(
                '/event_management.EventManagement/SearchEvents',
                request_serializer=event__management__pb2.SearchCriteria.SerializeToString,
                response_deserializer=event__management__pb2.EventList.FromString,
                _registered_method=True)
        self.PurchaseTicket = channel.unary_unary(
                '/event_management.EventManagement/PurchaseTicket',
                request_serializer=event__management__pb2.TicketRequest.SerializeToString,
                response_deserializer=event__management__pb2.TicketResponse.FromString,
                _registered_method=True)
        self.GetUserEvents = channel.unary_unary(
                '/event_management.EventManagement/GetUserEvents',
                request_serializer=event__management__pb2.UserID.SerializeToString,
                response_deserializer=event__management__pb2.EventList.FromString,
                _registered_method=True)


class EventManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurchaseTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEvent,
                    request_deserializer=event__management__pb2.Event.FromString,
                    response_serializer=event__management__pb2.EventResponse.SerializeToString,
            ),
            'UpdateEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEvent,
                    request_deserializer=event__management__pb2.Event.FromString,
                    response_serializer=event__management__pb2.EventResponse.SerializeToString,
            ),
            'GetEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvent,
                    request_deserializer=event__management__pb2.EventID.FromString,
                    response_serializer=event__management__pb2.Event.SerializeToString,
            ),
            'SearchEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchEvents,
                    request_deserializer=event__management__pb2.SearchCriteria.FromString,
                    response_serializer=event__management__pb2.EventList.SerializeToString,
            ),
            'PurchaseTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseTicket,
                    request_deserializer=event__management__pb2.TicketRequest.FromString,
                    response_serializer=event__management__pb2.TicketResponse.SerializeToString,
            ),
            'GetUserEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserEvents,
                    request_deserializer=event__management__pb2.UserID.FromString,
                    response_serializer=event__management__pb2.EventList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'event_management.EventManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('event_management.EventManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/event_management.EventManagement/CreateEvent',
            event__management__pb2.Event.SerializeToString,
            event__management__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/event_management.EventManagement/UpdateEvent',
            event__management__pb2.Event.SerializeToString,
            event__management__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/event_management.EventManagement/GetEvent',
            event__management__pb2.EventID.SerializeToString,
            event__management__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/event_management.EventManagement/SearchEvents',
            event__management__pb2.SearchCriteria.SerializeToString,
            event__management__pb2.EventList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurchaseTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/event_management.EventManagement/PurchaseTicket',
            event__management__pb2.TicketRequest.SerializeToString,
            event__management__pb2.TicketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/event_management.EventManagement/GetUserEvents',
            event__management__pb2.UserID.SerializeToString,
            event__management__pb2.EventList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
