FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
# RUN apt-get update && apt-get install -y python3-dev default-libmysqlclient-dev build-essential && rm -rf /var/lib/apt/lists/*
# RUN pip install -r requirements.txt

COPY . .

CMD ["python", "app.py"]
